name: Deploying to Server

on: 
  push:
    branches:
      - "production"

jobs:
  Redeploy:
    name: Deploying everything to Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Execute Remote Commands via SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.KNOWN_HOSTS }}" >> ~/.ssh/known_hosts


          ssh -i ~/.ssh/id_rsa ubuntu@15.207.16.227 << 'EOF'

            export PATH="/home/ubuntu/.nvm/versions/node/v24.12.0/bin:$PATH"
            
            cd /home/ubuntu/InkCalibur || exit
            
            git pull origin main

            pnpm install
            pnpm run build
            
            pm2 restart http-server ws-server frontend
          EOF